version: '3.4'

services:
  auth-sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: auth_db
    user: root
    restart: on-failure
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=MySup4rStrongP@ssword@@
      # - SA_USERNAME=sa
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - ./sqlserver-data/auth:/var/opt/mssql/data
  metadata-sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: metadata_db
    user: root
    restart: on-failure
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=MySup4rStrongP@ssword@@
      - MSSQL_PID=Express
    ports:
      - "1434:1433"
    volumes:
      - ./sqlserver-data/metadata:/var/opt/mssql/data
  ocelotgw:
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    ports:
      - "8000:80"
    depends_on:
      - auth.api
      - document.api
      - metadata.api
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  auth.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    depends_on:
      - auth-sqlserver
    ports:
      - "8001:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  document.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    ports:
      - "8003:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  metadata.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    depends_on:
      - metadata-sqlserver
    ports:
      - "8002:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  